version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-09-01T23-53-36Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    hostname: minio
    volumes:
      - minio-storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/fotostash;
      /usr/bin/mc anonymous set public myminio/fotostash;
      exit 0;
      "
  
  app:
    image: ghcr.io/shane-ducksbury/fotostash-app:latest
    ports: 
      - "3000:3000"
  
  api:
    image: ghcr.io/shane-ducksbury/fotostash-api:latest
    ports:
      - "5050:5050"


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-storage: